---
title: "100 Years of Pie"
format:
  jasa-pdf:
    keep-tex: true  
    journal:
      blinded: false
  jasa-html: default
date: last-modified
author:
  - name: Heike Hofmann
    acknowledgements: | 
      The authors gratefully acknowledge _please remember to list all relevant funding sources in the non-anonymized (unblinded) version_.
    affiliations:
      - name: Iowa State University
        department: Department of Statistics
  - name: Susan Vanderplas
    affiliations:
      - name: University of Nebraska, Lincoln
        department: Department of Statistics
abstract: |
  The text of your abstract. 200 or fewer words.
keywords:
  - 3 to 6 keywords
  - that do not appear in the title
bibliography: "`r rbbt::bbt_write_bib('zotero.bib', overwrite = TRUE, library_id=rbbt::bbt_library_id('Graphics Research'))`"
---

Outline:
- Introduction
    - Pie vs. Bar shade from early publications - debate for 100 years at least, but we cannot rule out that this disagreement was fundamental to the extinction of the dinosaurs
    - Pie chart has been attributed to Playfair - cite friendly et al.
    - The debate over pies vs. bars may be the motivation of the early user studies of statistical graphics, but these studies have since been the victim of overhype and extrapolation well beyond the bounds of the studies themselves. 
    - The aim of this paper is to examine the historical studies examining pie and bar charts, identifying what each study measured, what the reasonable conclusions are, and how the study was interpreted in later follow-up studies.

## Introduction {#sec-intro}

<!-- - Note that figures and tables (such as @fig-first and @tbl-one) should appear in the paper, not at the end or in separate files. -->
<!-- - In document front matter, you may set the key `blinded` under a `journal` key to hide the authors and acknowledgements, producing the required anonymized version. -->
<!-- - Remember that in the anonymized version, you should not identify authors indirectly in the text.  That is, don't say "In Smith et. al.  (2009) we showed that ...". Instead, say "Smith et. al. (2009) showed that ...". -->
<!-- - These points are only intended to remind you of some requirements. -->
<!-- Please refer to the instructions for authors -->
<!-- at [http://amstat.tandfonline.com/action/authorSubmission?journalCode=uasa20&page=instructions#.VFkk7fnF_0c](http://amstat.tandfonline.com/action/authorSubmission?journalCode=uasa20&page=instructions#.VFkk7fnF_0c) -->
<!-- - For more about ASA\ style, please see [https://files.taylorandfrancis.com/asa-style-guide.pdf](https://files.taylorandfrancis.com/asa-style-guide.pdf). -->



## Conclusion {#sec-conc}

## Disclosure statement

<!-- The authors have the following conflicts of interest to declare (or replace with a statement that no conflicts of interest exist). -->

## Data Availability Statement

<!-- Deidentified data have been made available at the following URL: XX. -->

## Supplementary Material {.supplementary}

<!-- Title: -->

<!-- :   Brief description. (file type) -->

<!-- ## BibTeX  -->

<!-- We encourage you to use BibTeX. -->
<!-- If you have, please feel free to use the package natbib with any bibliography style you're comfortable with. The .bst file agsm has been included here for your convenience.  -->
